import RegularInducedSubgraph.Basic
import RegularInducedSubgraph.CertifiedHandoff
import RegularInducedSubgraph.Modular
import RegularInducedSubgraph.Problem
import RegularInducedSubgraph.Ramsey
import RegularInducedSubgraph.Threshold
